// 옐(엘 덱) 일러스트를 스캔해서 색상 → 일러스트 URL 배열을 생성한다.
//   기본 이미지: public/images/hY/hY0N.png   (N = 색상 인덱스)
//   추가 변형  : public/images/SY/hY0N-*.png  (SY 폴더에 넣기만 하면 자동 인식)
//
// 색상 인덱스: 1=백(white) 2=녹(green) 3=적(red) 4=청(blue) 5=자(purple) 6=황(yellow)
//
// 결과: src/data/cheerImageVariantsMap.generated.ts
// 사용: npm run gen:variants  (또는 build/dev 의 prebuild/predev 훅으로 자동 실행)

import { readdirSync, statSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/images";
const HY_DIR = join(ROOT, "hY"); // 기본 옐 이미지
const SY_DIR = join(ROOT, "SY"); // 추가 옐 변형

// 색상 인덱스(파일명 hY0N) → 색상 키
const COLOR_BY_INDEX = {
  1: "white",
  2: "green",
  3: "red",
  4: "blue",
  5: "purple",
  6: "yellow",
};

const IMG_EXT = /\.(png|jpe?g|webp)$/i;

/** 폴더에서 옐 이미지 파일을 색상 인덱스별로 모은다. */
function scanCheerDir(dir, pattern) {
  const byIndex = new Map(); // index -> string[]
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return byIndex;
  for (const f of readdirSync(dir).sort()) {
    if (!IMG_EXT.test(f)) continue;
    const m = f.match(pattern);
    if (!m) continue;
    const idx = parseInt(m[1], 10);
    if (!COLOR_BY_INDEX[idx]) continue;
    const url = `/images/${dir.split(/[\\/]/).pop()}/${f}`;
    const arr = byIndex.get(idx) ?? [];
    arr.push(url);
    byIndex.set(idx, arr);
  }
  return byIndex;
}

// 기본: hY01.png ~ hY06.png   /   변형: hY01-013_SY.png 등 (hY0N-...)
const defaults = scanCheerDir(HY_DIR, /^hY0*(\d+)\.(?:png|jpe?g|webp)$/i);
const variants = scanCheerDir(SY_DIR, /^hY0*(\d+)-.*\.(?:png|jpe?g|webp)$/i);

/** SY 변형 정렬: 파일명 중간 번호(숫자) → 파일명 순. */
function variantNum(url) {
  const file = url.split("/").pop() ?? "";
  const m = file.match(/^hY0*\d+-0*(\d+)/i);
  return m ? parseInt(m[1], 10) : 0;
}

const result = {}; // colorKey -> string[]
for (let idx = 1; idx <= 6; idx++) {
  const color = COLOR_BY_INDEX[idx];
  const list = [];
  // 기본 이미지를 항상 맨 앞에 둔다.
  for (const u of (defaults.get(idx) ?? []).sort()) list.push(u);
  // SY 변형을 번호 순으로 뒤에 추가.
  const sy = (variants.get(idx) ?? []).sort(
    (a, b) => variantNum(a) - variantNum(b) || a.localeCompare(b),
  );
  for (const u of sy) if (!list.includes(u)) list.push(u);
  if (list.length > 0) result[color] = list;
}

const lines = [
  "// AUTO-GENERATED by scripts/genCheerImageVariants.mjs — do not edit by hand.",
  "// To regenerate: npm run gen:variants",
  "// 색상별 옐 일러스트 목록(첫 번째가 기본 hY, 그 뒤가 SY 변형).",
  "",
  "export const CHEER_IMAGE_VARIANTS: Record<string, string[]> = {",
];
for (const color of ["white", "green", "red", "blue", "purple", "yellow"]) {
  const urls = result[color];
  if (!urls) continue;
  lines.push(`  ${color}: [`);
  for (const u of urls) lines.push(`    "${u}",`);
  lines.push("  ],");
}
lines.push("};", "");

writeFileSync(
  "src/data/cheerImageVariantsMap.generated.ts",
  lines.join("\n"),
  "utf8",
);

const totalVariants = Object.values(result).reduce(
  (s, urls) => s + urls.length,
  0,
);
console.log(
  `[gen:cheer] ${Object.keys(result).length} colors, ${totalVariants} cheer images written.`,
);
