// public/images/ 의 카드 이미지를 스캔해서 cardId → 일러스트 URL 배열을 생성한다.
// 다중 일러스트(2장 이상)를 가진 카드만 매니페스트에 포함된다.
//
// 결과: src/data/cardImageVariantsMap.generated.ts
// 사용: npm run gen:variants  (또는 npm run build 의 prebuild 훅으로 자동 실행)

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/images";
// 카드가 아닌 보조 이미지 폴더 — 스킵
const SKIP_DIRS = new Set(["cost", "hY"]);

const groups = new Map(); // cardId -> string[]

for (const dir of readdirSync(ROOT).sort()) {
  if (SKIP_DIRS.has(dir)) continue;
  const dirPath = join(ROOT, dir);
  if (!statSync(dirPath).isDirectory()) continue;
  for (const f of readdirSync(dirPath).sort()) {
    if (!f.endsWith(".png")) continue;
    // <setId>-<num>(_<rest>)?.png
    const m = f.match(/^([a-zA-Z]+\d+-\d+)(?:_(.+))?\.png$/);
    if (!m) continue;
    const cardId = m[1];
    const url = `/images/${dir}/${f}`;
    const arr = groups.get(cardId) ?? [];
    arr.push(url);
    groups.set(cardId, arr);
  }
}

// 카드넘버 뒤 희귀도 글자로 일러스트 순서를 정한다 (작을수록 앞).
//   1번: OSR, C, U, R, RR / 2번: S / 3번: SR / 4번: UR / 5번: OUR
//   6번: SEC / (SEC와 P 사이) HR / 7번: P
// 같은 글자끼리는 그 뒤의 번호 순서대로 배치한다.
const RARITY_ORDER = [
  "OSR", "C", "U", "R", "RR", // 1번 그룹 (나열 순)
  "S",                        // 2번
  "SR",                       // 3번
  "UR",                       // 4번
  "OUR",                      // 5번
  "SEC",                      // 6번
  "HR",                       // SEC와 P 사이
  "P",                        // 7번
];
const RARITY_RANK = new Map(RARITY_ORDER.map((code, i) => [code, i]));
const UNKNOWN_RANK = RARITY_ORDER.length; // 미정의 코드(SY 등)는 맨 끝

// 파일 URL에서 [희귀도 랭크, 같은 글자 내 번호]를 뽑아낸다.
function variantSortKey(url) {
  const file = url.split("/").pop() ?? "";
  const m = file.match(/^[a-zA-Z]+\d+-\d+(?:_(.+))?\.png$/i);
  const rest = m?.[1];
  if (!rest) return { rank: -1, num: 0 }; // 접미사 없는 기본 일러스트 → 맨 앞
  let rank = UNKNOWN_RANK;
  let num = 0;
  for (const seg of rest.split("_")) {
    if (/^\d+$/.test(seg)) num = parseInt(seg, 10);
    else if (RARITY_RANK.has(seg.toUpperCase())) {
      rank = RARITY_RANK.get(seg.toUpperCase());
    }
  }
  return { rank, num };
}

for (const arr of groups.values()) {
  arr.sort((a, b) => {
    const ka = variantSortKey(a);
    const kb = variantSortKey(b);
    if (ka.rank !== kb.rank) return ka.rank - kb.rank;
    if (ka.num !== kb.num) return ka.num - kb.num;
    return a.localeCompare(b);
  });
}

const lines = [
  "// AUTO-GENERATED by scripts/genCardImageVariants.mjs — do not edit by hand.",
  "// To regenerate: npm run gen:variants",
  "",
  "export const CARD_IMAGE_VARIANTS: Record<string, string[]> = {",
];

const multi = [...groups.entries()]
  .filter(([, urls]) => urls.length > 1)
  .sort((a, b) => a[0].localeCompare(b[0]));

for (const [id, urls] of multi) {
  lines.push(`  "${id}": [`);
  for (const u of urls) lines.push(`    "${u}",`);
  lines.push("  ],");
}
lines.push("};", "");

writeFileSync(
  "src/data/cardImageVariantsMap.generated.ts",
  lines.join("\n"),
  "utf8",
);

console.log(
  `[gen:variants] ${groups.size} cards scanned, ${multi.length} multi-variant entries written.`,
);
