// public/images/ 의 카드 이미지를 스캔해서 cardId → 일러스트 URL 배열을 생성한다.
// 다중 일러스트(2장 이상)를 가진 카드만 매니페스트에 포함된다.
//
// 결과: src/data/cardImageVariantsMap.generated.ts
// 사용: npm run gen:variants  (또는 npm run build 의 prebuild 훅으로 자동 실행)

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/images";
// 카드가 아닌 보조 이미지 폴더 — 스킵
const SKIP_DIRS = new Set(["cost", "hY"]);

const groups = new Map(); // cardId -> string[]

for (const dir of readdirSync(ROOT).sort()) {
  if (SKIP_DIRS.has(dir)) continue;
  const dirPath = join(ROOT, dir);
  if (!statSync(dirPath).isDirectory()) continue;
  for (const f of readdirSync(dirPath).sort()) {
    if (!f.endsWith(".png")) continue;
    // <setId>-<num>(_<rest>)?.png
    const m = f.match(/^([a-zA-Z]+\d+-\d+)(?:_(.+))?\.png$/);
    if (!m) continue;
    const cardId = m[1];
    const url = `/images/${dir}/${f}`;
    const arr = groups.get(cardId) ?? [];
    arr.push(url);
    groups.set(cardId, arr);
  }
}

// SEC(시크릿 레어) 변형은 항상 마지막에 오도록 정렬.
// 같은 SEC 그룹/비-SEC 그룹 안에서는 알파벳 순.
const isSec = (url) => /_SEC(?:[_.]|$)/i.test(url);
for (const arr of groups.values()) {
  arr.sort((a, b) => {
    const sa = isSec(a) ? 1 : 0;
    const sb = isSec(b) ? 1 : 0;
    if (sa !== sb) return sa - sb;
    return a.localeCompare(b);
  });
}

const lines = [
  "// AUTO-GENERATED by scripts/genCardImageVariants.mjs — do not edit by hand.",
  "// To regenerate: npm run gen:variants",
  "",
  "export const CARD_IMAGE_VARIANTS: Record<string, string[]> = {",
];

const multi = [...groups.entries()]
  .filter(([, urls]) => urls.length > 1)
  .sort((a, b) => a[0].localeCompare(b[0]));

for (const [id, urls] of multi) {
  lines.push(`  "${id}": [`);
  for (const u of urls) lines.push(`    "${u}",`);
  lines.push("  ],");
}
lines.push("};", "");

writeFileSync(
  "src/data/cardImageVariantsMap.generated.ts",
  lines.join("\n"),
  "utf8",
);

console.log(
  `[gen:variants] ${groups.size} cards scanned, ${multi.length} multi-variant entries written.`,
);
