// AUTO-GENERATED by scripts/genCardImageVariants.mjs — do not edit by hand.
// To regenerate: npm run gen:variants

export const CARD_IMAGE_VARIANTS: Record<string, string[]> = {
  "hBP01-001": [
    "/images/hBP01/hBP01-001_OSR.png",
    "/images/hBP01/hBP01-001_OUR.png",
  ],
  "hBP01-002": [
    "/images/hBP01/hBP01-002_OSR.png",
    "/images/hBP01/hBP01-002_OUR.png",
  ],
  "hBP01-003": [
    "/images/hBP01/hBP01-003_OSR.png",
    "/images/hBP01/hBP01-003_OUR.png",
  ],
  "hBP01-004": [
    "/images/hBP01/hBP01-004_OSR.png",
    "/images/hBP01/hBP01-004_OUR.png",
    "/images/hBP01/hBP01-004_P.png",
  ],
  "hBP01-005": [
    "/images/hBP01/hBP01-005_OSR.png",
    "/images/hBP01/hBP01-005_OUR.png",
  ],
  "hBP01-006": [
    "/images/hBP01/hBP01-006_OSR.png",
    "/images/hBP01/hBP01-006_OUR.png",
    "/images/hBP01/hBP01-006_SEC.png",
  ],
  "hBP01-007": [
    "/images/hBP01/hBP01-007_OSR.png",
    "/images/hBP01/hBP01-007_OUR.png",
    "/images/hBP01/hBP01-007_P_01.png",
    "/images/hBP01/hBP01-007_P_02.png",
    "/images/hBP01/hBP01-007_P_03.png",
    "/images/hBP01/hBP01-007_P_04.png",
    "/images/hBP01/hBP01-007_SEC.png",
  ],
  "hBP01-008": [
    "/images/hBP01/hBP01-008_OSR.png",
    "/images/hBP01/hBP01-008_OUR.png",
  ],
  "hBP01-013": [
    "/images/hBP01/hBP01-013_P_02.png",
    "/images/hBP01/hBP01-013_P_03.png",
    "/images/hBP01/hBP01-013_R_02.png",
  ],
  "hBP01-014": [
    "/images/hBP01/hBP01-014_RR.png",
    "/images/hBP01/hBP01-014_UR.png",
  ],
  "hBP01-020": [
    "/images/hBP01/hBP01-020_P.png",
    "/images/hBP01/hBP01-020_R.png",
  ],
  "hBP01-022": [
    "/images/hBP01/hBP01-022_02_P.png",
    "/images/hBP01/hBP01-022_U.png",
  ],
  "hBP01-023": [
    "/images/hBP01/hBP01-023_RR.png",
    "/images/hBP01/hBP01-023_UR.png",
  ],
  "hBP01-024": [
    "/images/hBP01/hBP01-024_02_C.png",
    "/images/hBP01/hBP01-024_C.png",
    "/images/hBP01/hBP01-024_HR.png",
  ],
  "hBP01-027": [
    "/images/hBP01/hBP01-027_RR.png",
    "/images/hBP01/hBP01-027_UR.png",
  ],
  "hBP01-031": [
    "/images/hBP01/hBP01-031_P.png",
    "/images/hBP01/hBP01-031_R.png",
  ],
  "hBP01-032": [
    "/images/hBP01/hBP01-032_02_C.png",
    "/images/hBP01/hBP01-032_C.png",
    "/images/hBP01/hBP01-032_HR.png",
  ],
  "hBP01-037": [
    "/images/hBP01/hBP01-037_P.png",
    "/images/hBP01/hBP01-037_R.png",
  ],
  "hBP01-038": [
    "/images/hBP01/hBP01-038_02_C.png",
    "/images/hBP01/hBP01-038_C.png",
  ],
  "hBP01-041": [
    "/images/hBP01/hBP01-041_SR.png",
    "/images/hBP01/hBP01-041_U.png",
  ],
  "hBP01-042": [
    "/images/hBP01/hBP01-042_P.png",
    "/images/hBP01/hBP01-042_R.png",
  ],
  "hBP01-043": [
    "/images/hBP01/hBP01-043_RR.png",
    "/images/hBP01/hBP01-043_UR.png",
  ],
  "hBP01-044": [
    "/images/hBP01/hBP01-044_02_C.png",
    "/images/hBP01/hBP01-044_C.png",
    "/images/hBP01/hBP01-044_HR.png",
    "/images/hBP01/hBP01-044_P_02.png",
  ],
  "hBP01-047": [
    "/images/hBP01/hBP01-047_RR.png",
    "/images/hBP01/hBP01-047_UR.png",
  ],
  "hBP01-048": [
    "/images/hBP01/hBP01-048_03_C.png",
    "/images/hBP01/hBP01-048_C.png",
    "/images/hBP01/hBP01-048_HR.png",
  ],
  "hBP01-050": [
    "/images/hBP01/hBP01-050_P_03.png",
    "/images/hBP01/hBP01-050_U_02.png",
  ],
  "hBP01-051": [
    "/images/hBP01/hBP01-051_RR.png",
    "/images/hBP01/hBP01-051_UR.png",
  ],
  "hBP01-052": [
    "/images/hBP01/hBP01-052_02_C.png",
    "/images/hBP01/hBP01-052_C.png",
  ],
  "hBP01-055": [
    "/images/hBP01/hBP01-055_P.png",
    "/images/hBP01/hBP01-055_R.png",
  ],
  "hBP01-061": [
    "/images/hBP01/hBP01-061_P.png",
    "/images/hBP01/hBP01-061_R.png",
  ],
  "hBP01-066": [
    "/images/hBP01/hBP01-066_P.png",
    "/images/hBP01/hBP01-066_R.png",
  ],
  "hBP01-067": [
    "/images/hBP01/hBP01-067_RR.png",
    "/images/hBP01/hBP01-067_UR.png",
  ],
  "hBP01-068": [
    "/images/hBP01/hBP01-068_02_C.png",
    "/images/hBP01/hBP01-068_C.png",
    "/images/hBP01/hBP01-068_HR.png",
  ],
  "hBP01-070": [
    "/images/hBP01/hBP01-070_P_02.png",
    "/images/hBP01/hBP01-070_U.png",
  ],
  "hBP01-071": [
    "/images/hBP01/hBP01-071_RR.png",
    "/images/hBP01/hBP01-071_UR.png",
  ],
  "hBP01-072": [
    "/images/hBP01/hBP01-072_02_C.png",
    "/images/hBP01/hBP01-072_C.png",
  ],
  "hBP01-075": [
    "/images/hBP01/hBP01-075_P.png",
    "/images/hBP01/hBP01-075_R.png",
  ],
  "hBP01-076": [
    "/images/hBP01/hBP01-076_02_C.png",
    "/images/hBP01/hBP01-076_C.png",
    "/images/hBP01/hBP01-076_HR.png",
    "/images/hBP01/hBP01-076_P_2.png",
  ],
  "hBP01-077": [
    "/images/hBP01/hBP01-077_P.png",
    "/images/hBP01/hBP01-077_U.png",
  ],
  "hBP01-080": [
    "/images/hBP01/hBP01-080_P.png",
    "/images/hBP01/hBP01-080_R.png",
  ],
  "hBP01-081": [
    "/images/hBP01/hBP01-081_02_SR.png",
    "/images/hBP01/hBP01-081_RR_02.png",
    "/images/hBP01/hBP01-081_UR_02.png",
  ],
  "hBP01-082": [
    "/images/hBP01/hBP01-082_02_C.png",
    "/images/hBP01/hBP01-082_C.png",
  ],
  "hBP01-087": [
    "/images/hBP01/hBP01-087_P.png",
    "/images/hBP01/hBP01-087_R.png",
  ],
  "hBP01-088": [
    "/images/hBP01/hBP01-088_02_C.png",
    "/images/hBP01/hBP01-088_C.png",
  ],
  "hBP01-091": [
    "/images/hBP01/hBP01-091_RR.png",
    "/images/hBP01/hBP01-091_UR.png",
  ],
  "hBP01-092": [
    "/images/hBP01/hBP01-092_02_C.png",
    "/images/hBP01/hBP01-092_C.png",
    "/images/hBP01/hBP01-092_HR.png",
  ],
  "hBP01-095": [
    "/images/hBP01/hBP01-095_P.png",
    "/images/hBP01/hBP01-095_R.png",
  ],
  "hBP01-102": [
    "/images/hBP01/hBP01-102_P.png",
    "/images/hBP01/hBP01-102_U.png",
  ],
  "hBP01-104": [
    "/images/hBP01/hBP01-104_02_C.png",
    "/images/hBP01/hBP01-104_03_C.png",
    "/images/hBP01/hBP01-104_04_C.png",
    "/images/hBP01/hBP01-104_05_C.png",
    "/images/hBP01/hBP01-104_06_C.png",
    "/images/hBP01/hBP01-104_07_C.png",
    "/images/hBP01/hBP01-104_C.png",
    "/images/hBP01/hBP01-104_SR.png",
  ],
  "hBP01-108": [
    "/images/hBP01/hBP01-108_P.png",
    "/images/hBP01/hBP01-108_U.png",
  ],
  "hBP01-113": [
    "/images/hBP01/hBP01-113_P.png",
    "/images/hBP01/hBP01-113_U.png",
  ],
  "hBP01-126": [
    "/images/hBP01/hBP01-126_C.png",
    "/images/hBP01/hBP01-126_P_02.png",
  ],
  "hBP02-001": [
    "/images/hBP02/hBP02-001_OSR.png",
    "/images/hBP02/hBP02-001_OUR.png",
    "/images/hBP02/hBP02-001_SEC.png",
  ],
  "hBP02-002": [
    "/images/hBP02/hBP02-002_OSR.png",
    "/images/hBP02/hBP02-002_OUR.png",
  ],
  "hBP02-003": [
    "/images/hBP02/hBP02-003_OSR.png",
    "/images/hBP02/hBP02-003_OUR.png",
    "/images/hBP02/hBP02-003_SEC.png",
  ],
  "hBP02-004": [
    "/images/hBP02/hBP02-004_OSR.png",
    "/images/hBP02/hBP02-004_OUR.png",
    "/images/hBP02/hBP02-004_SEC.png",
  ],
  "hBP02-005": [
    "/images/hBP02/hBP02-005_OSR.png",
    "/images/hBP02/hBP02-005_OUR.png",
  ],
  "hBP02-006": [
    "/images/hBP02/hBP02-006_OSR.png",
    "/images/hBP02/hBP02-006_OUR.png",
  ],
  "hBP02-007": [
    "/images/hBP02/hBP02-007_OSR.png",
    "/images/hBP02/hBP02-007_OUR.png",
  ],
  "hBP02-008": [
    "/images/hBP02/hBP02-008_02_C.png",
    "/images/hBP02/hBP02-008_C.png",
    "/images/hBP02/hBP02-008_P.png",
  ],
  "hBP02-009": [
    "/images/hBP02/hBP02-009_P.png",
    "/images/hBP02/hBP02-009_U.png",
  ],
  "hBP02-011": [
    "/images/hBP02/hBP02-011_P_02.png",
    "/images/hBP02/hBP02-011_U.png",
  ],
  "hBP02-012": [
    "/images/hBP02/hBP02-012_R.png",
    "/images/hBP02/hBP02-012_SR.png",
  ],
  "hBP02-013": [
    "/images/hBP02/hBP02-013_02_SR.png",
    "/images/hBP02/hBP02-013_RR.png",
    "/images/hBP02/hBP02-013_SR.png",
    "/images/hBP02/hBP02-013_UR.png",
  ],
  "hBP02-014": [
    "/images/hBP02/hBP02-014_02_C.png",
    "/images/hBP02/hBP02-014_C.png",
    "/images/hBP02/hBP02-014_HR.png",
  ],
  "hBP02-016": [
    "/images/hBP02/hBP02-016_SR.png",
    "/images/hBP02/hBP02-016_U.png",
  ],
  "hBP02-017": [
    "/images/hBP02/hBP02-017_RR.png",
    "/images/hBP02/hBP02-017_SR.png",
    "/images/hBP02/hBP02-017_UR.png",
  ],
  "hBP02-019": [
    "/images/hBP02/hBP02-019_P.png",
    "/images/hBP02/hBP02-019_U.png",
  ],
  "hBP02-022": [
    "/images/hBP02/hBP02-022_R.png",
    "/images/hBP02/hBP02-022_SR.png",
  ],
  "hBP02-023": [
    "/images/hBP02/hBP02-023_RR.png",
    "/images/hBP02/hBP02-023_SR.png",
    "/images/hBP02/hBP02-023_UR.png",
  ],
  "hBP02-024": [
    "/images/hBP02/hBP02-024_02_C.png",
    "/images/hBP02/hBP02-024_C.png",
    "/images/hBP02/hBP02-024_P_02.png",
  ],
  "hBP02-026": [
    "/images/hBP02/hBP02-026_SR.png",
    "/images/hBP02/hBP02-026_U.png",
  ],
  "hBP02-027": [
    "/images/hBP02/hBP02-027_RR.png",
    "/images/hBP02/hBP02-027_SR.png",
    "/images/hBP02/hBP02-027_UR.png",
  ],
  "hBP02-028": [
    "/images/hBP02/hBP02-028_C.png",
    "/images/hBP02/hBP02-028_P_2.png",
  ],
  "hBP02-029": [
    "/images/hBP02/hBP02-029_P.png",
    "/images/hBP02/hBP02-029_U.png",
  ],
  "hBP02-031": [
    "/images/hBP02/hBP02-031_SR.png",
    "/images/hBP02/hBP02-031_U.png",
  ],
  "hBP02-032": [
    "/images/hBP02/hBP02-032_P.png",
    "/images/hBP02/hBP02-032_R.png",
    "/images/hBP02/hBP02-032_SR.png",
  ],
  "hBP02-033": [
    "/images/hBP02/hBP02-033_RR.png",
    "/images/hBP02/hBP02-033_SR.png",
    "/images/hBP02/hBP02-033_UR.png",
  ],
  "hBP02-034": [
    "/images/hBP02/hBP02-034_RR.png",
    "/images/hBP02/hBP02-034_SR.png",
    "/images/hBP02/hBP02-034_UR.png",
  ],
  "hBP02-039": [
    "/images/hBP02/hBP02-039_R.png",
    "/images/hBP02/hBP02-039_SR.png",
  ],
  "hBP02-040": [
    "/images/hBP02/hBP02-040_RR.png",
    "/images/hBP02/hBP02-040_SR.png",
    "/images/hBP02/hBP02-040_UR.png",
  ],
  "hBP02-041": [
    "/images/hBP02/hBP02-041_RR.png",
    "/images/hBP02/hBP02-041_SR.png",
    "/images/hBP02/hBP02-041_UR.png",
  ],
  "hBP02-043": [
    "/images/hBP02/hBP02-043_P.png",
    "/images/hBP02/hBP02-043_U.png",
  ],
  "hBP02-046": [
    "/images/hBP02/hBP02-046_R.png",
    "/images/hBP02/hBP02-046_SR.png",
  ],
  "hBP02-047": [
    "/images/hBP02/hBP02-047_P.png",
    "/images/hBP02/hBP02-047_RR.png",
    "/images/hBP02/hBP02-047_SR.png",
    "/images/hBP02/hBP02-047_UR.png",
  ],
  "hBP02-052": [
    "/images/hBP02/hBP02-052_R.png",
    "/images/hBP02/hBP02-052_SR.png",
  ],
  "hBP02-053": [
    "/images/hBP02/hBP02-053_RR.png",
    "/images/hBP02/hBP02-053_SR.png",
    "/images/hBP02/hBP02-053_UR.png",
  ],
  "hBP02-054": [
    "/images/hBP02/hBP02-054_02_C.png",
    "/images/hBP02/hBP02-054_03_P.png",
    "/images/hBP02/hBP02-054_C.png",
    "/images/hBP02/hBP02-054_HR.png",
  ],
  "hBP02-058": [
    "/images/hBP02/hBP02-058_R.png",
    "/images/hBP02/hBP02-058_SR.png",
  ],
  "hBP02-059": [
    "/images/hBP02/hBP02-059_RR.png",
    "/images/hBP02/hBP02-059_SR.png",
    "/images/hBP02/hBP02-059_UR.png",
  ],
  "hBP02-060": [
    "/images/hBP02/hBP02-060_R.png",
    "/images/hBP02/hBP02-060_SR.png",
  ],
  "hBP02-064": [
    "/images/hBP02/hBP02-064_RR.png",
    "/images/hBP02/hBP02-064_SR.png",
    "/images/hBP02/hBP02-064_UR.png",
  ],
  "hBP02-065": [
    "/images/hBP02/hBP02-065_02_C.png",
    "/images/hBP02/hBP02-065_C.png",
    "/images/hBP02/hBP02-065_HR.png",
  ],
  "hBP02-067": [
    "/images/hBP02/hBP02-067_P.png",
    "/images/hBP02/hBP02-067_U.png",
  ],
  "hBP02-068": [
    "/images/hBP02/hBP02-068_R.png",
    "/images/hBP02/hBP02-068_SR.png",
  ],
  "hBP02-069": [
    "/images/hBP02/hBP02-069_R.png",
    "/images/hBP02/hBP02-069_SR.png",
  ],
  "hBP02-070": [
    "/images/hBP02/hBP02-070_R.png",
    "/images/hBP02/hBP02-070_SR.png",
  ],
  "hBP02-071": [
    "/images/hBP02/hBP02-071_R.png",
    "/images/hBP02/hBP02-071_SR.png",
  ],
  "hBP02-072": [
    "/images/hBP02/hBP02-072_R.png",
    "/images/hBP02/hBP02-072_SR.png",
  ],
  "hBP02-073": [
    "/images/hBP02/hBP02-073_R.png",
    "/images/hBP02/hBP02-073_SR.png",
  ],
  "hBP02-074": [
    "/images/hBP02/hBP02-074_R.png",
    "/images/hBP02/hBP02-074_SR.png",
  ],
  "hBP02-076": [
    "/images/hBP02/hBP02-076_C.png",
    "/images/hBP02/hBP02-076_SR.png",
  ],
  "hBP02-077": [
    "/images/hBP02/hBP02-077_C.png",
    "/images/hBP02/hBP02-077_SR.png",
  ],
  "hBP02-079": [
    "/images/hBP02/hBP02-079_P.png",
    "/images/hBP02/hBP02-079_U.png",
  ],
  "hBP02-080": [
    "/images/hBP02/hBP02-080_P_2.png",
    "/images/hBP02/hBP02-080_U.png",
  ],
  "hBP02-084": [
    "/images/hBP02/hBP02-084_02_SR.png",
    "/images/hBP02/hBP02-084_02_U.png",
    "/images/hBP02/hBP02-084_U.png",
    "/images/hBP02/hBP02-084_SEC.png",
  ],
  "hBP02-085": [
    "/images/hBP02/hBP02-085_02_P.png",
    "/images/hBP02/hBP02-085_U_02.png",
    "/images/hBP02/hBP02-085_U.png",
  ],
  "hBP03-001": [
    "/images/hBP03/hBP03-001_OSR.png",
    "/images/hBP03/hBP03-001_OUR.png",
  ],
  "hBP03-002": [
    "/images/hBP03/hBP03-002_OSR.png",
    "/images/hBP03/hBP03-002_OUR.png",
    "/images/hBP03/hBP03-002_SEC.png",
  ],
  "hBP03-003": [
    "/images/hBP03/hBP03-003_OSR.png",
    "/images/hBP03/hBP03-003_OUR.png",
    "/images/hBP03/hBP03-003_SEC.png",
  ],
  "hBP03-004": [
    "/images/hBP03/hBP03-004_OSR.png",
    "/images/hBP03/hBP03-004_OUR.png",
  ],
  "hBP03-005": [
    "/images/hBP03/hBP03-005_OSR.png",
    "/images/hBP03/hBP03-005_OUR.png",
    "/images/hBP03/hBP03-005_SEC.png",
  ],
  "hBP03-006": [
    "/images/hBP03/hBP03-006_OSR.png",
    "/images/hBP03/hBP03-006_OUR.png",
    "/images/hBP03/hBP03-006_P.png",
  ],
  "hBP03-007": [
    "/images/hBP03/hBP03-007_OSR.png",
    "/images/hBP03/hBP03-007_OUR.png",
    "/images/hBP03/hBP03-007_SEC.png",
  ],
  "hBP03-008": [
    "/images/hBP03/hBP03-008_OSR.png",
    "/images/hBP03/hBP03-008_OUR.png",
  ],
  "hBP03-009": [
    "/images/hBP03/hBP03-009_02_C.png",
    "/images/hBP03/hBP03-009_C.png",
  ],
  "hBP03-013": [
    "/images/hBP03/hBP03-013_R.png",
    "/images/hBP03/hBP03-013_SR.png",
  ],
  "hBP03-014": [
    "/images/hBP03/hBP03-014_P.png",
    "/images/hBP03/hBP03-014_RR.png",
    "/images/hBP03/hBP03-014_SR.png",
    "/images/hBP03/hBP03-014_UR.png",
  ],
  "hBP03-015": [
    "/images/hBP03/hBP03-015_RR.png",
    "/images/hBP03/hBP03-015_SR.png",
    "/images/hBP03/hBP03-015_UR.png",
  ],
  "hBP03-020": [
    "/images/hBP03/hBP03-020_P.png",
    "/images/hBP03/hBP03-020_R.png",
    "/images/hBP03/hBP03-020_SR.png",
  ],
  "hBP03-021": [
    "/images/hBP03/hBP03-021_RR.png",
    "/images/hBP03/hBP03-021_SR.png",
    "/images/hBP03/hBP03-021_UR.png",
  ],
  "hBP03-022": [
    "/images/hBP03/hBP03-022_R.png",
    "/images/hBP03/hBP03-022_SR.png",
  ],
  "hBP03-023": [
    "/images/hBP03/hBP03-023_R.png",
    "/images/hBP03/hBP03-023_SR.png",
  ],
  "hBP03-024": [
    "/images/hBP03/hBP03-024_RR.png",
    "/images/hBP03/hBP03-024_SR.png",
    "/images/hBP03/hBP03-024_UR.png",
  ],
  "hBP03-025": [
    "/images/hBP03/hBP03-025_02_HR.png",
    "/images/hBP03/hBP03-025_C.png",
  ],
  "hBP03-026": [
    "/images/hBP03/hBP03-026_P.png",
    "/images/hBP03/hBP03-026_U.png",
  ],
  "hBP03-029": [
    "/images/hBP03/hBP03-029_R.png",
    "/images/hBP03/hBP03-029_SR.png",
  ],
  "hBP03-030": [
    "/images/hBP03/hBP03-030_02_SR.png",
    "/images/hBP03/hBP03-030_P.png",
    "/images/hBP03/hBP03-030_RR.png",
    "/images/hBP03/hBP03-030_SR.png",
    "/images/hBP03/hBP03-030_UR.png",
  ],
  "hBP03-031": [
    "/images/hBP03/hBP03-031_02_C.png",
    "/images/hBP03/hBP03-031_C.png",
  ],
  "hBP03-034": [
    "/images/hBP03/hBP03-034_RR.png",
    "/images/hBP03/hBP03-034_SR.png",
    "/images/hBP03/hBP03-034_UR.png",
  ],
  "hBP03-035": [
    "/images/hBP03/hBP03-035_R.png",
    "/images/hBP03/hBP03-035_SR.png",
  ],
  "hBP03-036": [
    "/images/hBP03/hBP03-036_P.png",
    "/images/hBP03/hBP03-036_R.png",
    "/images/hBP03/hBP03-036_SR.png",
  ],
  "hBP03-039": [
    "/images/hBP03/hBP03-039_R.png",
    "/images/hBP03/hBP03-039_SR.png",
  ],
  "hBP03-043": [
    "/images/hBP03/hBP03-043_RR.png",
    "/images/hBP03/hBP03-043_SR.png",
    "/images/hBP03/hBP03-043_UR.png",
  ],
  "hBP03-044": [
    "/images/hBP03/hBP03-044_R.png",
    "/images/hBP03/hBP03-044_SR_2.png",
    "/images/hBP03/hBP03-044_SR.png",
  ],
  "hBP03-045": [
    "/images/hBP03/hBP03-045_R.png",
    "/images/hBP03/hBP03-045_SR.png",
  ],
  "hBP03-049": [
    "/images/hBP03/hBP03-049_R.png",
    "/images/hBP03/hBP03-049_SR.png",
  ],
  "hBP03-050": [
    "/images/hBP03/hBP03-050_R.png",
    "/images/hBP03/hBP03-050_SR.png",
  ],
  "hBP03-051": [
    "/images/hBP03/hBP03-051_C.png",
    "/images/hBP03/hBP03-051_P_02.png",
  ],
  "hBP03-054": [
    "/images/hBP03/hBP03-054_P.png",
    "/images/hBP03/hBP03-054_U.png",
  ],
  "hBP03-055": [
    "/images/hBP03/hBP03-055_R.png",
    "/images/hBP03/hBP03-055_SR_2.png",
    "/images/hBP03/hBP03-055_SR.png",
  ],
  "hBP03-056": [
    "/images/hBP03/hBP03-056_RR.png",
    "/images/hBP03/hBP03-056_SR.png",
    "/images/hBP03/hBP03-056_UR.png",
  ],
  "hBP03-057": [
    "/images/hBP03/hBP03-057_02_C.png",
    "/images/hBP03/hBP03-057_C.png",
  ],
  "hBP03-059": [
    "/images/hBP03/hBP03-059_P.png",
    "/images/hBP03/hBP03-059_U.png",
  ],
  "hBP03-060": [
    "/images/hBP03/hBP03-060_R.png",
    "/images/hBP03/hBP03-060_SR.png",
  ],
  "hBP03-061": [
    "/images/hBP03/hBP03-061_02_C.png",
    "/images/hBP03/hBP03-061_C.png",
  ],
  "hBP03-065": [
    "/images/hBP03/hBP03-065_R.png",
    "/images/hBP03/hBP03-065_SR.png",
  ],
  "hBP03-066": [
    "/images/hBP03/hBP03-066_RR.png",
    "/images/hBP03/hBP03-066_SR.png",
    "/images/hBP03/hBP03-066_UR.png",
  ],
  "hBP03-067": [
    "/images/hBP03/hBP03-067_02_C.png",
    "/images/hBP03/hBP03-067_C.png",
    "/images/hBP03/hBP03-067_HR.png",
  ],
  "hBP03-071": [
    "/images/hBP03/hBP03-071_R.png",
    "/images/hBP03/hBP03-071_SR.png",
  ],
  "hBP03-072": [
    "/images/hBP03/hBP03-072_RR.png",
    "/images/hBP03/hBP03-072_SR.png",
    "/images/hBP03/hBP03-072_UR.png",
  ],
  "hBP03-076": [
    "/images/hBP03/hBP03-076_P.png",
    "/images/hBP03/hBP03-076_U.png",
  ],
  "hBP03-077": [
    "/images/hBP03/hBP03-077_R.png",
    "/images/hBP03/hBP03-077_SR.png",
  ],
  "hBP03-078": [
    "/images/hBP03/hBP03-078_RR.png",
    "/images/hBP03/hBP03-078_SR.png",
    "/images/hBP03/hBP03-078_UR.png",
  ],
  "hBP03-079": [
    "/images/hBP03/hBP03-079_RR.png",
    "/images/hBP03/hBP03-079_SR.png",
    "/images/hBP03/hBP03-079_UR.png",
  ],
  "hBP03-083": [
    "/images/hBP03/hBP03-083_R.png",
    "/images/hBP03/hBP03-083_SR.png",
  ],
  "hBP03-088": [
    "/images/hBP03/hBP03-088_P_1.png",
    "/images/hBP03/hBP03-088_P_2.png",
    "/images/hBP03/hBP03-088_P_3.png",
    "/images/hBP03/hBP03-088_U.png",
  ],
  "hBP03-092": [
    "/images/hBP03/hBP03-092_P.png",
    "/images/hBP03/hBP03-092_U.png",
  ],
  "hBP03-093": [
    "/images/hBP03/hBP03-093_02_P.png",
    "/images/hBP03/hBP03-093_U_02.png",
    "/images/hBP03/hBP03-093_U.png",
  ],
  "hBP03-105": [
    "/images/hBP03/hBP03-105_P_02.png",
    "/images/hBP03/hBP03-105_U.png",
  ],
  "hBP03-107": [
    "/images/hBP03/hBP03-107_P.png",
    "/images/hBP03/hBP03-107_U.png",
  ],
  "hBP03-112": [
    "/images/hBP03/hBP03-112_P_02.png",
    "/images/hBP03/hBP03-112_U.png",
  ],
  "hBP04-001": [
    "/images/hBP04/hBP04-001_OSR.png",
    "/images/hBP04/hBP04-001_OUR.png",
    "/images/hBP04/hBP04-001_SEC.png",
  ],
  "hBP04-002": [
    "/images/hBP04/hBP04-002_OSR.png",
    "/images/hBP04/hBP04-002_OUR.png",
    "/images/hBP04/hBP04-002_P.png",
  ],
  "hBP04-003": [
    "/images/hBP04/hBP04-003_OSR.png",
    "/images/hBP04/hBP04-003_OUR.png",
    "/images/hBP04/hBP04-003_P.png",
  ],
  "hBP04-004": [
    "/images/hBP04/hBP04-004_OSR.png",
    "/images/hBP04/hBP04-004_OUR.png",
    "/images/hBP04/hBP04-004_SEC.png",
  ],
  "hBP04-005": [
    "/images/hBP04/hBP04-005_OSR.png",
    "/images/hBP04/hBP04-005_OUR.png",
    "/images/hBP04/hBP04-005_SEC.png",
  ],
  "hBP04-006": [
    "/images/hBP04/hBP04-006_OSR.png",
    "/images/hBP04/hBP04-006_OUR.png",
    "/images/hBP04/hBP04-006_SEC.png",
  ],
  "hBP04-007": [
    "/images/hBP04/hBP04-007_OSR.png",
    "/images/hBP04/hBP04-007_OUR.png",
  ],
  "hBP04-009": [
    "/images/hBP04/hBP04-009_P_02.png",
    "/images/hBP04/hBP04-009_U.png",
  ],
  "hBP04-012": [
    "/images/hBP04/hBP04-012_R.png",
    "/images/hBP04/hBP04-012_SR.png",
  ],
  "hBP04-013": [
    "/images/hBP04/hBP04-013_02_SR.png",
    "/images/hBP04/hBP04-013_P.png",
    "/images/hBP04/hBP04-013_RR.png",
    "/images/hBP04/hBP04-013_SR.png",
    "/images/hBP04/hBP04-013_UR.png",
  ],
  "hBP04-014": [
    "/images/hBP04/hBP04-014_R.png",
    "/images/hBP04/hBP04-014_SR.png",
  ],
  "hBP04-015": [
    "/images/hBP04/hBP04-015_R.png",
    "/images/hBP04/hBP04-015_SR.png",
  ],
  "hBP04-016": [
    "/images/hBP04/hBP04-016_02_C.png",
    "/images/hBP04/hBP04-016_C.png",
  ],
  "hBP04-019": [
    "/images/hBP04/hBP04-019_R.png",
    "/images/hBP04/hBP04-019_SR.png",
  ],
  "hBP04-024": [
    "/images/hBP04/hBP04-024_R.png",
    "/images/hBP04/hBP04-024_SR.png",
  ],
  "hBP04-025": [
    "/images/hBP04/hBP04-025_RR.png",
    "/images/hBP04/hBP04-025_SR.png",
    "/images/hBP04/hBP04-025_UR.png",
  ],
  "hBP04-026": [
    "/images/hBP04/hBP04-026_R.png",
    "/images/hBP04/hBP04-026_SR.png",
  ],
  "hBP04-027": [
    "/images/hBP04/hBP04-027_R.png",
    "/images/hBP04/hBP04-027_SR.png",
  ],
  "hBP04-031": [
    "/images/hBP04/hBP04-031_R.png",
    "/images/hBP04/hBP04-031_SR.png",
  ],
  "hBP04-036": [
    "/images/hBP04/hBP04-036_R.png",
    "/images/hBP04/hBP04-036_SR.png",
  ],
  "hBP04-037": [
    "/images/hBP04/hBP04-037_RR.png",
    "/images/hBP04/hBP04-037_SR.png",
    "/images/hBP04/hBP04-037_UR.png",
  ],
  "hBP04-038": [
    "/images/hBP04/hBP04-038_R.png",
    "/images/hBP04/hBP04-038_SR.png",
  ],
  "hBP04-042": [
    "/images/hBP04/hBP04-042_RR.png",
    "/images/hBP04/hBP04-042_SR.png",
    "/images/hBP04/hBP04-042_UR.png",
  ],
  "hBP04-043": [
    "/images/hBP04/hBP04-043_02_C.png",
    "/images/hBP04/hBP04-043_C.png",
    "/images/hBP04/hBP04-043_HR.png",
  ],
  "hBP04-044": [
    "/images/hBP04/hBP04-044_P.png",
    "/images/hBP04/hBP04-044_U.png",
  ],
  "hBP04-047": [
    "/images/hBP04/hBP04-047_R.png",
    "/images/hBP04/hBP04-047_SR.png",
  ],
  "hBP04-048": [
    "/images/hBP04/hBP04-048_P.png",
    "/images/hBP04/hBP04-048_RR.png",
    "/images/hBP04/hBP04-048_SR.png",
    "/images/hBP04/hBP04-048_UR.png",
  ],
  "hBP04-049": [
    "/images/hBP04/hBP04-049_R.png",
    "/images/hBP04/hBP04-049_SR.png",
  ],
  "hBP04-050": [
    "/images/hBP04/hBP04-050_03_C.png",
    "/images/hBP04/hBP04-050_C.png",
  ],
  "hBP04-053": [
    "/images/hBP04/hBP04-053_RR.png",
    "/images/hBP04/hBP04-053_SR.png",
    "/images/hBP04/hBP04-053_UR.png",
  ],
  "hBP04-054": [
    "/images/hBP04/hBP04-054_02_C.png",
    "/images/hBP04/hBP04-054_C.png",
    "/images/hBP04/hBP04-054_HR.png",
  ],
  "hBP04-058": [
    "/images/hBP04/hBP04-058_P.png",
    "/images/hBP04/hBP04-058_R.png",
    "/images/hBP04/hBP04-058_SR.png",
  ],
  "hBP04-059": [
    "/images/hBP04/hBP04-059_02_SR.png",
    "/images/hBP04/hBP04-059_RR.png",
    "/images/hBP04/hBP04-059_SR.png",
    "/images/hBP04/hBP04-059_UR.png",
  ],
  "hBP04-060": [
    "/images/hBP04/hBP04-060_R.png",
    "/images/hBP04/hBP04-060_SR.png",
  ],
  "hBP04-061": [
    "/images/hBP04/hBP04-061_R.png",
    "/images/hBP04/hBP04-061_SR.png",
  ],
  "hBP04-062": [
    "/images/hBP04/hBP04-062_P.png",
    "/images/hBP04/hBP04-062_R.png",
    "/images/hBP04/hBP04-062_SR.png",
  ],
  "hBP04-066": [
    "/images/hBP04/hBP04-066_RR.png",
    "/images/hBP04/hBP04-066_SR.png",
    "/images/hBP04/hBP04-066_UR.png",
  ],
  "hBP04-067": [
    "/images/hBP04/hBP04-067_02_C.png",
    "/images/hBP04/hBP04-067_C.png",
    "/images/hBP04/hBP04-067_HR.png",
  ],
  "hBP04-068": [
    "/images/hBP04/hBP04-068_P.png",
    "/images/hBP04/hBP04-068_U.png",
  ],
  "hBP04-071": [
    "/images/hBP04/hBP04-071_R.png",
    "/images/hBP04/hBP04-071_SR.png",
  ],
  "hBP04-072": [
    "/images/hBP04/hBP04-072_P_02.png",
    "/images/hBP04/hBP04-072_RR.png",
    "/images/hBP04/hBP04-072_SR.png",
    "/images/hBP04/hBP04-072_UR.png",
  ],
  "hBP04-074": [
    "/images/hBP04/hBP04-074_P_02.png",
    "/images/hBP04/hBP04-074_U.png",
  ],
  "hBP04-077": [
    "/images/hBP04/hBP04-077_R.png",
    "/images/hBP04/hBP04-077_SR.png",
  ],
  "hBP04-078": [
    "/images/hBP04/hBP04-078_RR.png",
    "/images/hBP04/hBP04-078_SR.png",
    "/images/hBP04/hBP04-078_UR.png",
  ],
  "hBP04-079": [
    "/images/hBP04/hBP04-079_02_C.png",
    "/images/hBP04/hBP04-079_C.png",
  ],
  "hBP04-081": [
    "/images/hBP04/hBP04-081_P.png",
    "/images/hBP04/hBP04-081_U.png",
  ],
  "hBP04-082": [
    "/images/hBP04/hBP04-082_RR.png",
    "/images/hBP04/hBP04-082_SR.png",
    "/images/hBP04/hBP04-082_UR.png",
  ],
  "hBP04-083": [
    "/images/hBP04/hBP04-083_02_C.png",
    "/images/hBP04/hBP04-083_C.png",
  ],
  "hBP04-086": [
    "/images/hBP04/hBP04-086_RR.png",
    "/images/hBP04/hBP04-086_SR.png",
    "/images/hBP04/hBP04-086_UR.png",
  ],
  "hBP04-091": [
    "/images/hBP04/hBP04-091_S.png",
    "/images/hBP04/hBP04-091_U.png",
  ],
  "hBP04-105": [
    "/images/hBP04/hBP04-105_S.png",
    "/images/hBP04/hBP04-105_U.png",
  ],
  "hBP05-001": [
    "/images/hBP05/hBP05-001_OSR.png",
    "/images/hBP05/hBP05-001_OUR.png",
  ],
  "hBP05-002": [
    "/images/hBP05/hBP05-002_OSR.png",
    "/images/hBP05/hBP05-002_OUR.png",
    "/images/hBP05/hBP05-002_SEC.png",
  ],
  "hBP05-003": [
    "/images/hBP05/hBP05-003_OSR.png",
    "/images/hBP05/hBP05-003_OUR.png",
    "/images/hBP05/hBP05-003_SEC.png",
  ],
  "hBP05-004": [
    "/images/hBP05/hBP05-004_OSR.png",
    "/images/hBP05/hBP05-004_OUR.png",
  ],
  "hBP05-005": [
    "/images/hBP05/hBP05-005_OSR.png",
    "/images/hBP05/hBP05-005_OUR.png",
    "/images/hBP05/hBP05-005_SEC.png",
  ],
  "hBP05-006": [
    "/images/hBP05/hBP05-006_OSR.png",
    "/images/hBP05/hBP05-006_OUR.png",
  ],
  "hBP05-007": [
    "/images/hBP05/hBP05-007_OSR.png",
    "/images/hBP05/hBP05-007_OUR.png",
  ],
  "hBP05-009": [
    "/images/hBP05/hBP05-009_C.png",
    "/images/hBP05/hBP05-009_P.png",
  ],
  "hBP05-010": [
    "/images/hBP05/hBP05-010_P.png",
    "/images/hBP05/hBP05-010_U.png",
  ],
  "hBP05-011": [
    "/images/hBP05/hBP05-011_P.png",
    "/images/hBP05/hBP05-011_R.png",
    "/images/hBP05/hBP05-011_SR.png",
  ],
  "hBP05-012": [
    "/images/hBP05/hBP05-012_RR.png",
    "/images/hBP05/hBP05-012_SR.png",
    "/images/hBP05/hBP05-012_UR.png",
  ],
  "hBP05-013": [
    "/images/hBP05/hBP05-013_R.png",
    "/images/hBP05/hBP05-013_SR.png",
  ],
  "hBP05-014": [
    "/images/hBP05/hBP05-014_C.png",
    "/images/hBP05/hBP05-014_P.png",
  ],
  "hBP05-016": [
    "/images/hBP05/hBP05-016_RR.png",
    "/images/hBP05/hBP05-016_SR.png",
    "/images/hBP05/hBP05-016_UR.png",
    "/images/hBP05/hBP05-016_SEC.png",
  ],
  "hBP05-017": [
    "/images/hBP05/hBP05-017_R.png",
    "/images/hBP05/hBP05-017_SR.png",
  ],
  "hBP05-018": [
    "/images/hBP05/hBP05-018_R.png",
    "/images/hBP05/hBP05-018_SR.png",
  ],
  "hBP05-022": [
    "/images/hBP05/hBP05-022_R.png",
    "/images/hBP05/hBP05-022_SR.png",
  ],
  "hBP05-023": [
    "/images/hBP05/hBP05-023_RR.png",
    "/images/hBP05/hBP05-023_SR.png",
    "/images/hBP05/hBP05-023_UR.png",
  ],
  "hBP05-024": [
    "/images/hBP05/hBP05-024_R.png",
    "/images/hBP05/hBP05-024_SR.png",
  ],
  "hBP05-027": [
    "/images/hBP05/hBP05-027_RR.png",
    "/images/hBP05/hBP05-027_SR.png",
    "/images/hBP05/hBP05-027_UR.png",
  ],
  "hBP05-028": [
    "/images/hBP05/hBP05-028_R.png",
    "/images/hBP05/hBP05-028_SR.png",
  ],
  "hBP05-029": [
    "/images/hBP05/hBP05-029_R.png",
    "/images/hBP05/hBP05-029_SR.png",
  ],
  "hBP05-031": [
    "/images/hBP05/hBP05-031_C.png",
    "/images/hBP05/hBP05-031_P_02.png",
  ],
  "hBP05-033": [
    "/images/hBP05/hBP05-033_R.png",
    "/images/hBP05/hBP05-033_SR.png",
  ],
  "hBP05-034": [
    "/images/hBP05/hBP05-034_RR.png",
    "/images/hBP05/hBP05-034_SR.png",
    "/images/hBP05/hBP05-034_UR.png",
  ],
  "hBP05-035": [
    "/images/hBP05/hBP05-035_R.png",
    "/images/hBP05/hBP05-035_SR.png",
  ],
  "hBP05-036": [
    "/images/hBP05/hBP05-036_C.png",
    "/images/hBP05/hBP05-036_P.png",
  ],
  "hBP05-037": [
    "/images/hBP05/hBP05-037_P.png",
    "/images/hBP05/hBP05-037_RR.png",
    "/images/hBP05/hBP05-037_SR.png",
    "/images/hBP05/hBP05-037_UR.png",
  ],
  "hBP05-038": [
    "/images/hBP05/hBP05-038_R.png",
    "/images/hBP05/hBP05-038_SR.png",
  ],
  "hBP05-039": [
    "/images/hBP05/hBP05-039_R.png",
    "/images/hBP05/hBP05-039_SR.png",
  ],
  "hBP05-043": [
    "/images/hBP05/hBP05-043_SR.png",
    "/images/hBP05/hBP05-043_U.png",
  ],
  "hBP05-044": [
    "/images/hBP05/hBP05-044_P.png",
    "/images/hBP05/hBP05-044_R.png",
    "/images/hBP05/hBP05-044_SR.png",
  ],
  "hBP05-045": [
    "/images/hBP05/hBP05-045_RR.png",
    "/images/hBP05/hBP05-045_SR.png",
    "/images/hBP05/hBP05-045_UR.png",
  ],
  "hBP05-046": [
    "/images/hBP05/hBP05-046_R.png",
    "/images/hBP05/hBP05-046_SR.png",
  ],
  "hBP05-048": [
    "/images/hBP05/hBP05-048_P.png",
    "/images/hBP05/hBP05-048_U.png",
  ],
  "hBP05-049": [
    "/images/hBP05/hBP05-049_RR.png",
    "/images/hBP05/hBP05-049_SR.png",
    "/images/hBP05/hBP05-049_UR.png",
  ],
  "hBP05-050": [
    "/images/hBP05/hBP05-050_R.png",
    "/images/hBP05/hBP05-050_SR.png",
  ],
  "hBP05-051": [
    "/images/hBP05/hBP05-051_R.png",
    "/images/hBP05/hBP05-051_SR.png",
  ],
  "hBP05-055": [
    "/images/hBP05/hBP05-055_R.png",
    "/images/hBP05/hBP05-055_SR.png",
  ],
  "hBP05-056": [
    "/images/hBP05/hBP05-056_RR.png",
    "/images/hBP05/hBP05-056_SR.png",
    "/images/hBP05/hBP05-056_UR.png",
  ],
  "hBP05-060": [
    "/images/hBP05/hBP05-060_R.png",
    "/images/hBP05/hBP05-060_SR.png",
  ],
  "hBP05-061": [
    "/images/hBP05/hBP05-061_RR_02.png",
    "/images/hBP05/hBP05-061_SR_02.png",
    "/images/hBP05/hBP05-061_UR_02.png",
  ],
  "hBP05-062": [
    "/images/hBP05/hBP05-062_R.png",
    "/images/hBP05/hBP05-062_SR.png",
  ],
  "hBP05-066": [
    "/images/hBP05/hBP05-066_R.png",
    "/images/hBP05/hBP05-066_SR.png",
  ],
  "hBP05-067": [
    "/images/hBP05/hBP05-067_RR.png",
    "/images/hBP05/hBP05-067_SR.png",
    "/images/hBP05/hBP05-067_UR.png",
  ],
  "hBP05-068": [
    "/images/hBP05/hBP05-068_C.png",
    "/images/hBP05/hBP05-068_P.png",
  ],
  "hBP05-069": [
    "/images/hBP05/hBP05-069_SR.png",
    "/images/hBP05/hBP05-069_U.png",
  ],
  "hBP05-070": [
    "/images/hBP05/hBP05-070_RR.png",
    "/images/hBP05/hBP05-070_SR.png",
    "/images/hBP05/hBP05-070_UR.png",
  ],
  "hBP05-071": [
    "/images/hBP05/hBP05-071_R.png",
    "/images/hBP05/hBP05-071_SR.png",
  ],
  "hBP05-072": [
    "/images/hBP05/hBP05-072_R.png",
    "/images/hBP05/hBP05-072_SR.png",
  ],
  "hBP05-073": [
    "/images/hBP05/hBP05-073_R.png",
    "/images/hBP05/hBP05-073_SR.png",
  ],
  "hBP05-074": [
    "/images/hBP05/hBP05-074_02_C.png",
    "/images/hBP05/hBP05-074_C.png",
    "/images/hBP05/hBP05-074_P.png",
  ],
  "hBP05-075": [
    "/images/hBP05/hBP05-075_C.png",
    "/images/hBP05/hBP05-075_P.png",
  ],
  "hBP05-079": [
    "/images/hBP05/hBP05-079_01_P.png",
    "/images/hBP05/hBP05-079_02_P.png",
    "/images/hBP05/hBP05-079_U.png",
  ],
  "hBP05-080": [
    "/images/hBP05/hBP05-080_P.png",
    "/images/hBP05/hBP05-080_SR.png",
    "/images/hBP05/hBP05-080_U.png",
    "/images/hBP05/hBP05-080_SEC.png",
  ],
  "hBP06-001": [
    "/images/hBP06/hBP06-001_OSR.png",
    "/images/hBP06/hBP06-001_OUR.png",
    "/images/hBP06/hBP06-001_SEC.png",
  ],
  "hBP06-002": [
    "/images/hBP06/hBP06-002_OSR.png",
    "/images/hBP06/hBP06-002_OUR.png",
  ],
  "hBP06-003": [
    "/images/hBP06/hBP06-003_OSR.png",
    "/images/hBP06/hBP06-003_OUR.png",
    "/images/hBP06/hBP06-003_SEC.png",
  ],
  "hBP06-004": [
    "/images/hBP06/hBP06-004_OSR.png",
    "/images/hBP06/hBP06-004_OUR.png",
    "/images/hBP06/hBP06-004_SEC.png",
  ],
  "hBP06-005": [
    "/images/hBP06/hBP06-005_OSR.png",
    "/images/hBP06/hBP06-005_OUR.png",
  ],
  "hBP06-006": [
    "/images/hBP06/hBP06-006_OSR.png",
    "/images/hBP06/hBP06-006_OUR.png",
  ],
  "hBP06-007": [
    "/images/hBP06/hBP06-007_OSR.png",
    "/images/hBP06/hBP06-007_OUR.png",
  ],
  "hBP06-008": [
    "/images/hBP06/hBP06-008_OSR.png",
    "/images/hBP06/hBP06-008_OUR.png",
    "/images/hBP06/hBP06-008_SEC.png",
  ],
  "hBP06-013": [
    "/images/hBP06/hBP06-013_R.png",
    "/images/hBP06/hBP06-013_SR.png",
  ],
  "hBP06-014": [
    "/images/hBP06/hBP06-014_RR.png",
    "/images/hBP06/hBP06-014_SR.png",
    "/images/hBP06/hBP06-014_UR.png",
  ],
  "hBP06-015": [
    "/images/hBP06/hBP06-015_C.png",
    "/images/hBP06/hBP06-015_HR.png",
  ],
  "hBP06-019": [
    "/images/hBP06/hBP06-019_R.png",
    "/images/hBP06/hBP06-019_SR.png",
  ],
  "hBP06-020": [
    "/images/hBP06/hBP06-020_RR.png",
    "/images/hBP06/hBP06-020_SR.png",
    "/images/hBP06/hBP06-020_UR.png",
  ],
  "hBP06-021": [
    "/images/hBP06/hBP06-021_R.png",
    "/images/hBP06/hBP06-021_SR.png",
  ],
  "hBP06-022": [
    "/images/hBP06/hBP06-022_C.png",
    "/images/hBP06/hBP06-022_P.png",
  ],
  "hBP06-026": [
    "/images/hBP06/hBP06-026_R.png",
    "/images/hBP06/hBP06-026_SR.png",
  ],
  "hBP06-027": [
    "/images/hBP06/hBP06-027_RR.png",
    "/images/hBP06/hBP06-027_SR.png",
    "/images/hBP06/hBP06-027_UR.png",
  ],
  "hBP06-030": [
    "/images/hBP06/hBP06-030_R.png",
    "/images/hBP06/hBP06-030_SR.png",
  ],
  "hBP06-031": [
    "/images/hBP06/hBP06-031_RR.png",
    "/images/hBP06/hBP06-031_SR.png",
    "/images/hBP06/hBP06-031_UR.png",
  ],
  "hBP06-032": [
    "/images/hBP06/hBP06-032_R.png",
    "/images/hBP06/hBP06-032_SR.png",
  ],
  "hBP06-033": [
    "/images/hBP06/hBP06-033_P.png",
    "/images/hBP06/hBP06-033_R.png",
    "/images/hBP06/hBP06-033_SR.png",
  ],
  "hBP06-034": [
    "/images/hBP06/hBP06-034_C.png",
    "/images/hBP06/hBP06-034_P.png",
  ],
  "hBP06-038": [
    "/images/hBP06/hBP06-038_R.png",
    "/images/hBP06/hBP06-038_SR.png",
  ],
  "hBP06-039": [
    "/images/hBP06/hBP06-039_P.png",
    "/images/hBP06/hBP06-039_RR.png",
    "/images/hBP06/hBP06-039_SR.png",
    "/images/hBP06/hBP06-039_UR.png",
  ],
  "hBP06-043": [
    "/images/hBP06/hBP06-043_P.png",
    "/images/hBP06/hBP06-043_U.png",
  ],
  "hBP06-044": [
    "/images/hBP06/hBP06-044_R.png",
    "/images/hBP06/hBP06-044_SR.png",
  ],
  "hBP06-045": [
    "/images/hBP06/hBP06-045_RR.png",
    "/images/hBP06/hBP06-045_SR.png",
    "/images/hBP06/hBP06-045_UR.png",
  ],
  "hBP06-046": [
    "/images/hBP06/hBP06-046_R.png",
    "/images/hBP06/hBP06-046_SR.png",
  ],
  "hBP06-047": [
    "/images/hBP06/hBP06-047_R.png",
    "/images/hBP06/hBP06-047_SR.png",
  ],
  "hBP06-052": [
    "/images/hBP06/hBP06-052_R.png",
    "/images/hBP06/hBP06-052_SR.png",
  ],
  "hBP06-053": [
    "/images/hBP06/hBP06-053_RR.png",
    "/images/hBP06/hBP06-053_SR.png",
    "/images/hBP06/hBP06-053_UR.png",
  ],
  "hBP06-054": [
    "/images/hBP06/hBP06-054_R.png",
    "/images/hBP06/hBP06-054_SR.png",
  ],
  "hBP06-055": [
    "/images/hBP06/hBP06-055_R.png",
    "/images/hBP06/hBP06-055_SR.png",
  ],
  "hBP06-056": [
    "/images/hBP06/hBP06-056_R.png",
    "/images/hBP06/hBP06-056_SR.png",
  ],
  "hBP06-057": [
    "/images/hBP06/hBP06-057_C.png",
    "/images/hBP06/hBP06-057_P.png",
  ],
  "hBP06-058": [
    "/images/hBP06/hBP06-058_SR.png",
    "/images/hBP06/hBP06-058_U.png",
  ],
  "hBP06-059": [
    "/images/hBP06/hBP06-059_R.png",
    "/images/hBP06/hBP06-059_SR.png",
  ],
  "hBP06-060": [
    "/images/hBP06/hBP06-060_RR.png",
    "/images/hBP06/hBP06-060_SR.png",
    "/images/hBP06/hBP06-060_UR.png",
  ],
  "hBP06-065": [
    "/images/hBP06/hBP06-065_R.png",
    "/images/hBP06/hBP06-065_SR.png",
  ],
  "hBP06-066": [
    "/images/hBP06/hBP06-066_RR.png",
    "/images/hBP06/hBP06-066_SR.png",
    "/images/hBP06/hBP06-066_UR.png",
  ],
  "hBP06-067": [
    "/images/hBP06/hBP06-067_C.png",
    "/images/hBP06/hBP06-067_P.png",
  ],
  "hBP06-069": [
    "/images/hBP06/hBP06-069_R.png",
    "/images/hBP06/hBP06-069_SR.png",
  ],
  "hBP06-070": [
    "/images/hBP06/hBP06-070_RR.png",
    "/images/hBP06/hBP06-070_SR.png",
    "/images/hBP06/hBP06-070_UR.png",
  ],
  "hBP06-071": [
    "/images/hBP06/hBP06-071_R.png",
    "/images/hBP06/hBP06-071_SR.png",
  ],
  "hBP06-076": [
    "/images/hBP06/hBP06-076_R.png",
    "/images/hBP06/hBP06-076_SR.png",
  ],
  "hBP06-077": [
    "/images/hBP06/hBP06-077_RR.png",
    "/images/hBP06/hBP06-077_SR.png",
    "/images/hBP06/hBP06-077_UR.png",
  ],
  "hBP06-080": [
    "/images/hBP06/hBP06-080_R.png",
    "/images/hBP06/hBP06-080_SR.png",
  ],
  "hBP06-081": [
    "/images/hBP06/hBP06-081_RR.png",
    "/images/hBP06/hBP06-081_SR.png",
    "/images/hBP06/hBP06-081_UR.png",
  ],
  "hBP06-082": [
    "/images/hBP06/hBP06-082_R.png",
    "/images/hBP06/hBP06-082_SR.png",
  ],
  "hBP06-083": [
    "/images/hBP06/hBP06-083_R.png",
    "/images/hBP06/hBP06-083_SR.png",
  ],
  "hBP06-090": [
    "/images/hBP06/hBP06-090_P.png",
    "/images/hBP06/hBP06-090_SR.png",
    "/images/hBP06/hBP06-090_U.png",
  ],
  "hBP07-001": [
    "/images/hBP07/hBP07-001_OSR.png",
    "/images/hBP07/hBP07-001_OUR.png",
    "/images/hBP07/hBP07-001_P.png",
  ],
  "hBP07-002": [
    "/images/hBP07/hBP07-002_OSR.png",
    "/images/hBP07/hBP07-002_OUR.png",
    "/images/hBP07/hBP07-002_SEC.png",
  ],
  "hBP07-003": [
    "/images/hBP07/hBP07-003_OSR.png",
    "/images/hBP07/hBP07-003_OUR.png",
    "/images/hBP07/hBP07-003_SEC.png",
  ],
  "hBP07-004": [
    "/images/hBP07/hBP07-004_OSR.png",
    "/images/hBP07/hBP07-004_OUR.png",
  ],
  "hBP07-005": [
    "/images/hBP07/hBP07-005_OSR.png",
    "/images/hBP07/hBP07-005_OUR.png",
  ],
  "hBP07-006": [
    "/images/hBP07/hBP07-006_OSR.png",
    "/images/hBP07/hBP07-006_OUR.png",
    "/images/hBP07/hBP07-006_SEC.png",
  ],
  "hBP07-007": [
    "/images/hBP07/hBP07-007_OSR.png",
    "/images/hBP07/hBP07-007_OUR.png",
    "/images/hBP07/hBP07-007_SEC.png",
  ],
  "hBP07-009": [
    "/images/hBP07/hBP07-009_P.png",
    "/images/hBP07/hBP07-009_U.png",
  ],
  "hBP07-012": [
    "/images/hBP07/hBP07-012_R.png",
    "/images/hBP07/hBP07-012_SR.png",
  ],
  "hBP07-014": [
    "/images/hBP07/hBP07-014_RR.png",
    "/images/hBP07/hBP07-014_SR.png",
    "/images/hBP07/hBP07-014_UR.png",
  ],
  "hBP07-019": [
    "/images/hBP07/hBP07-019_R.png",
    "/images/hBP07/hBP07-019_SR.png",
  ],
  "hBP07-021": [
    "/images/hBP07/hBP07-021_RR.png",
    "/images/hBP07/hBP07-021_SR.png",
    "/images/hBP07/hBP07-021_UR.png",
  ],
  "hBP07-022": [
    "/images/hBP07/hBP07-022_R.png",
    "/images/hBP07/hBP07-022_SR.png",
  ],
  "hBP07-027": [
    "/images/hBP07/hBP07-027_R.png",
    "/images/hBP07/hBP07-027_SR.png",
  ],
  "hBP07-028": [
    "/images/hBP07/hBP07-028_P.png",
    "/images/hBP07/hBP07-028_U.png",
  ],
  "hBP07-029": [
    "/images/hBP07/hBP07-029_RR.png",
    "/images/hBP07/hBP07-029_SR.png",
    "/images/hBP07/hBP07-029_UR.png",
  ],
  "hBP07-030": [
    "/images/hBP07/hBP07-030_R.png",
    "/images/hBP07/hBP07-030_SR.png",
  ],
  "hBP07-031": [
    "/images/hBP07/hBP07-031_R.png",
    "/images/hBP07/hBP07-031_SR.png",
  ],
  "hBP07-034": [
    "/images/hBP07/hBP07-034_R.png",
    "/images/hBP07/hBP07-034_SR.png",
  ],
  "hBP07-035": [
    "/images/hBP07/hBP07-035_RR.png",
    "/images/hBP07/hBP07-035_SR.png",
    "/images/hBP07/hBP07-035_UR.png",
  ],
  "hBP07-040": [
    "/images/hBP07/hBP07-040_R.png",
    "/images/hBP07/hBP07-040_SR.png",
  ],
  "hBP07-042": [
    "/images/hBP07/hBP07-042_RR.png",
    "/images/hBP07/hBP07-042_SR.png",
    "/images/hBP07/hBP07-042_UR.png",
  ],
  "hBP07-043": [
    "/images/hBP07/hBP07-043_P_01.png",
    "/images/hBP07/hBP07-043_P_02.png",
    "/images/hBP07/hBP07-043_R.png",
    "/images/hBP07/hBP07-043_SR.png",
  ],
  "hBP07-044": [
    "/images/hBP07/hBP07-044_R.png",
    "/images/hBP07/hBP07-044_SR.png",
  ],
  "hBP07-045": [
    "/images/hBP07/hBP07-045_R.png",
    "/images/hBP07/hBP07-045_SR.png",
  ],
  "hBP07-048": [
    "/images/hBP07/hBP07-048_R.png",
    "/images/hBP07/hBP07-048_SR.png",
  ],
  "hBP07-049": [
    "/images/hBP07/hBP07-049_RR.png",
    "/images/hBP07/hBP07-049_SR.png",
    "/images/hBP07/hBP07-049_UR.png",
  ],
  "hBP07-054": [
    "/images/hBP07/hBP07-054_R.png",
    "/images/hBP07/hBP07-054_SR.png",
  ],
  "hBP07-056": [
    "/images/hBP07/hBP07-056_RR.png",
    "/images/hBP07/hBP07-056_SR.png",
    "/images/hBP07/hBP07-056_UR.png",
  ],
  "hBP07-057": [
    "/images/hBP07/hBP07-057_R.png",
    "/images/hBP07/hBP07-057_SR.png",
  ],
  "hBP07-058": [
    "/images/hBP07/hBP07-058_R.png",
    "/images/hBP07/hBP07-058_SR.png",
  ],
  "hBP07-061": [
    "/images/hBP07/hBP07-061_R.png",
    "/images/hBP07/hBP07-061_SR.png",
  ],
  "hBP07-062": [
    "/images/hBP07/hBP07-062_RR.png",
    "/images/hBP07/hBP07-062_SR.png",
    "/images/hBP07/hBP07-062_UR.png",
  ],
  "hBP07-066": [
    "/images/hBP07/hBP07-066_C.png",
    "/images/hBP07/hBP07-066_SR.png",
  ],
  "hBP07-067": [
    "/images/hBP07/hBP07-067_R.png",
    "/images/hBP07/hBP07-067_SR.png",
  ],
  "hBP07-068": [
    "/images/hBP07/hBP07-068_P.png",
    "/images/hBP07/hBP07-068_U.png",
  ],
  "hBP07-069": [
    "/images/hBP07/hBP07-069_RR.png",
    "/images/hBP07/hBP07-069_SR.png",
    "/images/hBP07/hBP07-069_UR.png",
  ],
  "hBP07-070": [
    "/images/hBP07/hBP07-070_R.png",
    "/images/hBP07/hBP07-070_SR.png",
  ],
  "hBP07-071": [
    "/images/hBP07/hBP07-071_C.png",
    "/images/hBP07/hBP07-071_P.png",
  ],
  "hBP07-073": [
    "/images/hBP07/hBP07-073_R.png",
    "/images/hBP07/hBP07-073_SR.png",
  ],
  "hBP07-074": [
    "/images/hBP07/hBP07-074_RR.png",
    "/images/hBP07/hBP07-074_SR.png",
    "/images/hBP07/hBP07-074_UR.png",
  ],
  "hBP07-075": [
    "/images/hBP07/hBP07-075_R.png",
    "/images/hBP07/hBP07-075_SR.png",
  ],
  "hBP07-076": [
    "/images/hBP07/hBP07-076_R.png",
    "/images/hBP07/hBP07-076_SR.png",
  ],
  "hBP07-081": [
    "/images/hBP07/hBP07-081_R.png",
    "/images/hBP07/hBP07-081_SR.png",
  ],
  "hBP07-083": [
    "/images/hBP07/hBP07-083_RR.png",
    "/images/hBP07/hBP07-083_SR.png",
    "/images/hBP07/hBP07-083_UR.png",
  ],
  "hBP07-084": [
    "/images/hBP07/hBP07-084_R.png",
    "/images/hBP07/hBP07-084_SR.png",
  ],
  "hBP07-085": [
    "/images/hBP07/hBP07-085_R.png",
    "/images/hBP07/hBP07-085_SR.png",
  ],
  "hBP07-086": [
    "/images/hBP07/hBP07-086_R.png",
    "/images/hBP07/hBP07-086_SR.png",
  ],
  "hBP07-089": [
    "/images/hBP07/hBP07-089_R.png",
    "/images/hBP07/hBP07-089_SR.png",
  ],
  "hBP07-090": [
    "/images/hBP07/hBP07-090_RR.png",
    "/images/hBP07/hBP07-090_SR.png",
    "/images/hBP07/hBP07-090_UR.png",
  ],
  "hSD01-004": [
    "/images/hSD01/hSD01-004_P.png",
    "/images/hSD01/hSD01-004_R.png",
  ],
  "hSD01-006": [
    "/images/hSD01/hSD01-006_P.png",
    "/images/hSD01/hSD01-006_RR.png",
  ],
  "hSD01-009": [
    "/images/hSD01/hSD01-009_P.png",
    "/images/hSD01/hSD01-009_R.png",
  ],
  "hSD01-011": [
    "/images/hSD01/hSD01-011_P.png",
    "/images/hSD01/hSD01-011_RR.png",
  ],
  "hSD01-013": [
    "/images/hSD01/hSD01-013_P.png",
    "/images/hSD01/hSD01-013_R.png",
  ],
  "hSD01-016": [
    "/images/hSD01/hSD01-016_02_C.png",
    "/images/hSD01/hSD01-016_C.png",
    "/images/hSD01/hSD01-016_P_02.png",
  ],
  "hSD01-017": [
    "/images/hSD01/hSD01-017_02_C.png",
    "/images/hSD01/hSD01-017_C.png",
  ],
  "hSD01-018": [
    "/images/hSD01/hSD01-018_C.png",
    "/images/hSD01/hSD01-018_SR.png",
  ],
  "hSD01-019": [
    "/images/hSD01/hSD01-019_C_02.png",
    "/images/hSD01/hSD01-019_SR.png",
  ],
  "hSD02-002": [
    "/images/hSD02/hSD02-002_02_C.png",
    "/images/hSD02/hSD02-002_C.png",
    "/images/hSD02/hSD02-002_HR.png",
  ],
  "hSD02-007": [
    "/images/hSD02/hSD02-007_02_P.png",
    "/images/hSD02/hSD02-007_U.png",
  ],
  "hSD02-009": [
    "/images/hSD02/hSD02-009_RR.png",
    "/images/hSD02/hSD02-009_SR.png",
  ],
  "hSD03-002": [
    "/images/hSD03/hSD03-002_02_C.png",
    "/images/hSD03/hSD03-002_C.png",
    "/images/hSD03/hSD03-002_P_2.png",
  ],
  "hSD03-003": [
    "/images/hSD03/hSD03-003_C.png",
    "/images/hSD03/hSD03-003_P.png",
  ],
  "hSD03-009": [
    "/images/hSD03/hSD03-009_RR.png",
    "/images/hSD03/hSD03-009_SR.png",
  ],
  "hSD04-002": [
    "/images/hSD04/hSD04-002_02_C.png",
    "/images/hSD04/hSD04-002_C.png",
  ],
  "hSD04-009": [
    "/images/hSD04/hSD04-009_RR.png",
    "/images/hSD04/hSD04-009_SR.png",
  ],
  "hSD05-009": [
    "/images/hSD05/hSD05-009_RR.png",
    "/images/hSD05/hSD05-009_SR.png",
  ],
  "hSD06-006": [
    "/images/hSD06/hSD06-006_P.png",
    "/images/hSD06/hSD06-006_R.png",
  ],
  "hSD06-007": [
    "/images/hSD06/hSD06-007_RR.png",
    "/images/hSD06/hSD06-007_SR.png",
  ],
  "hSD07-002": [
    "/images/hSD07/hSD07-002_02_C.png",
    "/images/hSD07/hSD07-002_C.png",
    "/images/hSD07/hSD07-002_HR.png",
  ],
  "hSD07-007": [
    "/images/hSD07/hSD07-007_SR.png",
    "/images/hSD07/hSD07-007_U.png",
  ],
  "hSD07-009": [
    "/images/hSD07/hSD07-009_RR.png",
    "/images/hSD07/hSD07-009_SR.png",
  ],
  "hSD08-004": [
    "/images/hSD08/hSD08-004_P.png",
    "/images/hSD08/hSD08-004_RR.png",
  ],
  "hSD09-004": [
    "/images/hSD09/hSD09-004_P.png",
    "/images/hSD09/hSD09-004_RR.png",
  ],
  "hSD10-002": [
    "/images/hSD10/hSD10-002_02_C.png",
    "/images/hSD10/hSD10-002_C.png",
  ],
  "hSD10-006": [
    "/images/hSD10/hSD10-006_P.png",
    "/images/hSD10/hSD10-006_RR.png",
  ],
  "hSD10-009": [
    "/images/hSD10/hSD10-009_P.png",
    "/images/hSD10/hSD10-009_RR.png",
  ],
  "hSD10-010": [
    "/images/hSD10/hSD10-010_P.png",
    "/images/hSD10/hSD10-010_RR.png",
  ],
  "hSD10-012": [
    "/images/hSD10/hSD10-012_02_P.png",
    "/images/hSD10/hSD10-012_U.png",
  ],
  "hSD11-002": [
    "/images/hSD11/hSD11-002_02_C.png",
    "/images/hSD11/hSD11-002_C.png",
  ],
  "hSD11-006": [
    "/images/hSD11/hSD11-006_P.png",
    "/images/hSD11/hSD11-006_RR.png",
  ],
  "hSD11-009": [
    "/images/hSD11/hSD11-009_P.png",
    "/images/hSD11/hSD11-009_RR.png",
  ],
  "hSD12-007": [
    "/images/hSD12/hSD12-007_P.png",
    "/images/hSD12/hSD12-007_RR.png",
  ],
  "hSD12-011": [
    "/images/hSD12/hSD12-011_P.png",
    "/images/hSD12/hSD12-011_RR.png",
  ],
  "hSD13-007": [
    "/images/hSD13/hSD13-007_P.png",
    "/images/hSD13/hSD13-007_RR.png",
  ],
  "hSD13-013": [
    "/images/hSD13/hSD13-013_P.png",
    "/images/hSD13/hSD13-013_RR.png",
  ],
};
